on: 
  push:
    branches: ["qa"]

jobs:
  build:
    name: PrimeroJob
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Executando o STEP1
      run: |
        echo Esse processo carrega uma mensagem ESTOU NA QA
        echo basica para entender o workflow
